version: "3.9"

services:
  redis:
    image: redis:6.2.5-alpine
    restart: always
    ports:
      - 6379:6379
  postgres:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  elasticsearch:
    image: elasticsearch:7.14.1
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
     - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  mongo:
    image: mongo:5.0.3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

volumes:
  postgres:
  elasticsearch:
  mongo:
